### ISSUE TITLE
Compare MDS in flu with 2 vs 4 components in grid search

### ISSUE THREAD

**Issue by huddlej** [blab/cartography#11]
MDS with 2 components produces noticeably different embeddings and HDBSCAN clusters than MDS with 4 components.

For example, this is the seasonal flu MDS embedding with 2 components:

![EBA7DA05-06E2-4F96-9DDD-259F16B167F4](https://user-images.githubusercontent.com/85372/132047240-c390b570-9b39-4db0-bc86-3ea1d544679c.png)

And this is the MDS embedding for the same data with 4 components (only first two are shown, but note differences in clusters):

![5BA72D38-24AC-4A9A-8603-A717357729A7](https://user-images.githubusercontent.com/85372/132047285-f5f91262-c747-4f56-ba02-723a151109a0.png)

The correlation between genetic distance and embedding distance is much higher for the 4-component embedding (as we would expected), but we don't know if this embedding produces more accurate clusters.

We should update the grid search parameters file for seasonal flu's training data to include a column for MDS's `n_components` and re-run the grid search with these different values. We should update the script to summarize grid search results to identify the optimal number of components for MDS from validation MCC like we do for t-SNE and UMAP parameters. Then we should re-run the full MDS embedding with the optimal values and update the manuscript accordingly.

**Comment by nandsra21** [comment]
Just pushed a fix for this to the four main workflows, as well as summarize-grid-search. Whatever the best value is can be inputted into the embed script manually
