### ISSUE TITLE
Move pathogen-embed into its own repository

### ISSUE THREAD

**Issue by huddlej** [blab/cartography#32]
To simplify development of the software independently from the scientific publication, we should move the `embed` code into its own repository.

- [x] Create pathogen-embed repo in blab organization (John) -> https://github.com/blab/pathogen-embed
- [x] Move code from cartography repo into new repo (Sravani)
- [x] Setup and test docs, CI, etc. (Sravani)
- [x] Update PyPI to use new repo (Sravani)

**Comment by nandsra21** [comment]
Finished and uploaded: https://pypi.org/project/pathogen-embed/0.1.1/
