### ISSUE TITLE
Wildcard error with seasonal-flu snakefile

### ISSUE THREAD

**Issue by nandsra21** [blab/cartography#6]
![image](https://user-images.githubusercontent.com/40477441/125835564-0ae5facf-5ecd-46e6-acfd-501baad88fcd.png)

I'm not sure why this is happening since I have wildcard constraints:
`wildcard_constraints:
    methods="(pca|mds|t-sne|umap)",
    KDE_METHODS="(pca|mds|t-sne|umap|genetic)",
    internal_node= "(ancestral|sequences)"
`

**Comment by huddlej** [comment]
Closed by c66b5aef379af41978bb62ada66fdbb27bc0b20f
