### ISSUE TITLE
Manually assign better seasonal flu clade colors

### ISSUE THREAD

**Issue by huddlej** [blab/cartography#9]
The auto-assigned seasonal flu clade colors worked for a little while, but the latest iteration of the embeddings assigns colors that make related clades almost impossible to distinguish. Older clades that barely have any data get colors that should be used for larger extant clades.

For example, A2, A2/re, A3, and A4 are almost identically colored in the following figure:

![image](https://user-images.githubusercontent.com/85372/132046969-2db3eacd-759d-47f9-ac73-e309a00e46c0.png)

We should go back to manually assigning colors to these clades, since there are a fixed number of clades in the analyses.

**Comment by nandsra21** [comment]
Pushed a change to fix this. The old code has been made "raw" for now, but I can delete it completely if we decide these graphs look better.

**Comment by huddlej** [comment]
@nandsra21 Can you also use the same approach for 2018-2020 figure colors? Thank you!

**Comment by nandsra21** [comment]
We can reopen if needed - but for right now we're only making HDBSCAN figures so "colors" is fine.
